Fix mojoshader hlsl not emitting POSITION inputs with an index other than 0
icculus/mojoshader pull request #45
Opened 2021-06-15 18:50 UTC by kg

Fix mojoshader hlsl not emitting POSITION inputs with an index other than 0
Add an assert for the case where a buggy VS is missing outputs its PS needs (the shader will fail to compile anyway and produce a mystery crash later, so this is an improvement)

See https://gist.github.com/kg/33f3b1b3e51bc49ff4ae30ad05903f15 and https://gist.github.com/kg/ccd3a8b676a26346867735b61b83c7c6

2021-06-15 23:09 UTC, TheSpydog requested changes
One minor "style" fix, but beyond that everything looks good to me! I tested this with a handful of shader-sensitive games and didn't see any problems.

2021-06-15 23:09 UTC, TheSpydog commented on profiles/mojoshader_profile_hlsl.c
> +                }
```suggestion
                } // switch
```

2021-06-16 01:22 UTC, TheSpydog approved these changes

2021-06-16 02:13 UTC, flibitijibibo commented
Applied: https://hg.icculus.org/icculus/mojoshader/rev/f9b8e34cc41f

2021-06-16 02:13 UTC, closed without merging